package conf;
$SO        = "LINUX-x86_64";
$version   = "2";
$year      = "2019";
$database  = "energy";
#$database2 = "vhts";
#$database3 = "pubchem";
$ip        = "10.42.0.108";
$user      = "iect2019";
$pass      = "asd";
$PATH      = "/home/IECT";
$machine   = "fabian";
$nproc     = 16;
$ram       = "32GB";
1;
